# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: [ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.4' # The JDK version to make available on the path.
      - name: Maven build
        run: mvn clean package -Dquarkus.container-image.build=true
  deploy:
    needs: build
    runs-on: [ubuntu-18.04]
    steps:
      - name: Docker login
        uses: manusa/actions-publish-docker@master
        with:
          name: teamloan/teamloan-backend
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_password }}
          tag: dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.access_key_id }}
          aws-secret-access-key: ${{ secrets.secret_access_key }}
          aws-region: us-east-2
